### ISSUE TITLE
Using Maven apps DataFlowClientException:  File must exist

### ISSUE THREAD

**Issue by balistof** [spring-cloud/spring-cloud-dataflow-server-mesos#94]
When I try to deploy a Maven based stream I get following error in the shell:

`dataflow:>stream create --definition "time | log" --name ticktock
Created new stream 'ticktock'
dataflow:>stream deploy ticktock
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: File must exist`

Looking into the server logs I find:
`java.lang.IllegalArgumentException: File must exist
    at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:67) ~[spring-cloud-dataflow-server-mesos.jar!/:1.0.0.RELEASE]
    at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:51) ~[spring-cloud-dataflow-server-mesos.jar!/:1.0.0.RELEASE]
    at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:95) ~[spring-cloud-dataflow-server-mesos.jar!/:1.0.0.RELEASE]
    at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:65) ~[spring-cloud-dataflow-server-mesos.jar!/:1.0.0.RELEASE]
    at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61) ~[spring-cloud-dataflow-server-mesos.jar!/:1.0.0.RELEASE]`

Docker works just fine.

**Comment by shahbour** [comment]
i am having the same issue trying to deploy the ticktock on YARN . did you figure out what was the problem ?

**Comment by balistof** [comment]
Maven is not supported.
